name: Static code analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/ tests/
